name: Docs

on:
  push:
    branches: [main]
    paths:
      - "**.lua"
      - "**.md"
      - ".ldoc.lua"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Lua & LDoc
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.4 luarocks
          sudo luarocks install ldoc

      - name: Generate documentation
        run: |
          ldoc .ldoc.lua

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
